highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty

title: Thom Wright
tagline: Personal blog and website
description: Thom's blog and personal website

url: https://thomwright.co.uk
shorturl: thomwright.co.uk
baseurl: ""

author:
  name: Thom Wright

version: 1.0.0

github:
  repo: https://github.com/ThomWright/ThomWright.github.io

sass:
  sass_dir: public/css/_sass
  style: compressed

collections:
  failure-patterns:
    output: true

  draft:
    output: true

exclude:
- _config.yml
- .editorconfig
- .gitignore
- CNAME
- docker-compose.yml
- Gemfile
- Gemfile.lock
- provision
- README.md
- Vagrantfile
