# Dependencies
markdown:         kramdown
highligher:       pygments

# Permalinks
permalink:        pretty

# Setup
title:            Thom Wright
tagline:          Because tomwright.co.uk wasn't available...
description:      Thom's blog and personal website

url:              https://thomwright.co.uk
shorturl:         thomwright.co.uk
baseurl:          ""

author:
  name:           Thom Wright

version:          0.0.1

github:
  repo:           https://github.com/ThomWright/ThomWright.github.io

# Github can't cope with this :(
# source:           ./source

sass:
    sass_dir: public/css/_sass
    style: compressed
