highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty

title: Thom's Blog
description: Writing about software engineering

url: https://thomwright.co.uk
shorturl: thomwright.co.uk
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

author:
  name: Thom Wright

version: 1.0.0

github:
  repo: https://github.com/ThomWright/ThomWright.github.io

sass:
  sass_dir: public/css/_sass
  style: compressed

collections:
  failure-patterns:
    output: true

  # For publishing drafts
  wip:
    output: true

defaults:
  - scope:
      path: ""
      type: "wip"
    values:
      public: false
      sitemap: false
  - scope:
      path: ""
      type: "failure-patterns"
    values:
      layout: "pattern"


exclude:
- _config.yml
- .editorconfig
- .gitignore
- CNAME
- docker-compose.yml
- Gemfile
- Gemfile.lock
- provision
- README.md
- tmp
- Vagrantfile
