version: '3'
services:
  github-pages:
    image: jekyll/jekyll:4.2.0
    command: jekyll serve --incremental --drafts --watch --force_polling -H 0.0.0.0 -P 4000
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
    tty: true
    environment:
      JEKYLL_UID: 1001
      JEKYLL_GID: 1001
