version: '3'
services:
  github-pages:
    image: jekyll/jekyll:pages
    command: jekyll serve --drafts --watch --force_polling -H 0.0.0.0 -P 4000
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
    tty: true
